---
new_page_extension: md
auto_deploy: false
admin_path: public/admin/
webhook_url:
sections:
- type: document
  path: src/content/meta.json
  label: Meta
upload_dir: public/images/
public_path: ""
front_matter_path: ""
use_front_matter_path:
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
